export enum Genres {
  Fiction = "Fiction",
  NonFiction = "NonFiction",
  Mystery = "Mystery",
  ScienceFiction = "ScienceFiction",
  Fantasy = "Fantasy",
  Romance = "Romance",
  Thriller = "Thriller",
  Horror = "Horror",
  Biography = "Biography",
  SelfHelp = "Self Help",
  Science = "Science",
  Travel = "Travel",
  Poetry = "Poetry",
  Drama = "Drama",
  YoungAdult = "Young Adult",
  ChildrensLiterature = "Children",
  Crime = "Crime",
  Adventure = "Adventure",
  Philosophy = "Philosophy",
}
