export enum Genres {
  Fiction = "Fiction",
  NonFiction = "Non-Fiction",
  Mystery = "Mystery",
  ScienceFiction = "Science Fiction",
  Fantasy = "Fantasy",
  Romance = "Romance",
  Thriller = "Thriller",
  Horror = "Horror",
  Biography = "Biography/Autobiography",
  HistoricalFiction = "Historical Fiction",
  SelfHelp = "Self-Help",
  Science = "Science",
  Travel = "Travel",
  Poetry = "Poetry",
  Drama = "Drama/Play",
  YoungAdult = "Young Adult (YA)",
  ChildrensLiterature = "Children's Literature",
  Crime = "Crime",
  Adventure = "Adventure",
}
